version: "3.9"
services:
  client:
      build:
        context: ./frontend
        dockerfile: dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - db
        - server
  server:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    build:
      context: ./backend
      dockerfile: dockerfile.pg
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
