version: "3.9"
services:
  server:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    build:
      context: ./
      dockerfile: dockerfile.pg
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
